FROM nvidia/cuda:12.2.0-runtime-ubuntu20.04

RUN apt-get -y update && apt-get -y upgrade
RUN apt-get -y install python3 python3-pip curl
RUN curl -sSL https://install.python-poetry.org | python3 -
WORKDIR /app

COPY ./requirements-nvidia.txt /app/requirements.txt
RUN pip3 install --no-cache-dir --upgrade -r /app/requirements.txt

COPY /app/ /app/

ENTRYPOINT ["python3", "main.py"]

# If running behind a proxy like Nginx or Traefik add --proxy-headers
# CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80", "--proxy-headers"]